server:
  port: 9002
  #port: ${PORT:8080}  # Usa el puerto que Render le asigne dinámicamente
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_clienteventa
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:postgresql://dpg-d1m5crumcj7s739s6ptg-a/ventas_db_g4fp
    #username: ventas_db_g4fp_user
    #password: PbqWxx2GLKgq9kgGNGIocGNFXHKJKzPG
    #driver-class-name: org.postgresql.Driver
  #web:
    #resources:
      #static-locations: classpath:/static/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false
